### ISSUE TITLE
Import path in routes is broken

### ISSUE THREAD

**Issue by asdf123101** [toams69/vuejs-template#1]
The path reference to `HelloWorld.vue` seems to be broken when I run `npm run build`. 

https://github.com/toams69/vuejs-template/blob/e228569acd3fff4879f18d21bcf337dd4f4b16a3/template/src/webapp/router/routes.js#L1

`@` is resolved to `src` in [Vue Webpack template](https://github.com/vuejs-templates/webpack). The correct path thus should be `@/webapp/pages/HelloWorld` or `../pages/HelloWorld` without using `@`.

**Comment by toams69** [comment]
Thanks. This is resolved
